---
- name: Deploy Docker Compose stack and bulid Wazuh
  hosts: localhost
  become: yes

  tasks:
    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Clone specific version of wazuh-docker repo
      ansible.builtin.git:
        repo: https://github.com/wazuh/wazuh-docker.git
        dest: "{{ ansible_env.HOME }}/wazuh-docker"
        version: v4.12.0

    - name: Generate indexer certs
      community.docker.docker_compose:
        project_src: "{{ ansible_env.HOME }}/wazuh-docker"
        files:
          - generate-indexer-certs.yml
        build: false
        pull: false
        restarted: false
        removed: false
        state: present
        services:
          - generator
        stopped: false
        remove_orphans: false
        recreate: never
        run_once: true
        run_options:
          - --rm

    - name: Bring up Wazuh stack
      community.docker.docker_compose:
        project_src: "{{ ansible_env.HOME }}/wazuh-docker"
        state: present