---
# Assets
- name: Waiting for Dashboard API
  when: inventory_hostname == "wazuh-dashboard"
  ansible.builtin.uri:
    url: "https://localhost/api/status"
    method: GET
    headers:
      Authorization: "Basic {{ (initial_user ~ ':' ~ initial_pass) | b64encode }}"
    validate_certs: false
  register: kib_status
  retries: 20
  delay: 20
  until: kib_status.status == 200

- name: Import Dashboard Assets 1
  when: inventory_hostname == "wazuh-dashboard"
  ansible.builtin.uri:
    url: "https://localhost/api/saved_objects/_import?overwrite=true"
    method: POST
    headers:
      osd-xsrf: "true"
      Authorization: "Basic {{ (initial_user ~ ':' ~ initial_pass) | b64encode }}"
    body_format: form-multipart
    body:
      file:
        filename: "visualization.ndjson"
        content: "{{ lookup('file', role_path + '/files/visualization.ndjson') }}"
    status_code: 200
    validate_certs: false