---
# Assets
- name: V치rakoz치s a Dashboard API-ra
  ansible.builtin.uri:
    url: "https://localhost:443/api/status"
    method: GET
    validate_certs: false
  register: kib_status
  retries: 20
  delay: 6
  until: kib_status.status == 200

- name: Kibana (Wazuh dashboard) vizualiz치ci칩 import
  ansible.builtin.uri:
    url: "https://localhost:443/api/saved_objects/_import"
    method: POST
    headers:
      osd-xsrf: "true"
      Authorization: "Basic {{ (initial_user ~ ':' ~ initial_pass) | b64encode }}"
    body_format: form-multipart
    body:
      file:
        filename: "visualization.ndjson"
        mime_type: "application/ndjson"
        content: "{{ lookup('file', role_path + '/assets/visualization.ndjson') }}"
    status_code: 200
    validate_certs: false