---
# Configuration
- name: Insert a configuration block into the file
  ansible.builtin.blockinfile:
    path: /var/lib/docker/volumes/single-node_wazuh_etc/_data/shared/default/agent.conf
    block: |
      {% for integrity_check in integrity_checks %}
      <agent_config name="{{ integrity_check.agent }}">
        <syscheck>
          {% for dir in integrity_check.directories %}
          <directories whodata="yes">{{ dir }}</directories>
          {% endfor %}
        </syscheck>
      </agent_config>
      {% endfor %}