---
# Install Docker and Docker compose
- name: Install required system packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

# Deploy Wazuh stack
- name: Clone specific version of wazuh-docker repo
  ansible.builtin.git:
    repo: https://github.com/wazuh/wazuh-docker.git
    dest: "/home/ubuntu/blocks-lab/wazuh-docker"
    version: "{{ wazuh_version }}"

- name: Generate indexer certs with docker compose
  ansible.builtin.command: docker compose -f generate-indexer-certs.yml run --rm generator
  args:
    chdir: "/home/ubuntu/blocks-lab/wazuh-docker/single-node"
  when: firstrun == "yes"

- name: Bring up Wazuh stack
  community.docker.docker_compose_v2:
    project_src: "/home/ubuntu/blocks-lab/wazuh-docker/single-node"
    state: present

# Install Wazuh-ansible
- name: Clone specific version of wazuh-ansible repo
  ansible.builtin.git:
    repo: https://github.com/wazuh/wazuh-ansible.git
    dest: "/home/ubuntu/blocks-lab/wazuh-ansible"
    version: "{{ wazuh_version }}"

- name: Ensure symlink exists for wazuh role
  ansible.builtin.file:
    src: /home/ubuntu/blocks-lab/wazuh-ansible/roles/wazuh/ansible-wazuh-agent
    dest: /etc/ansible/roles/ansible-wazuh-agent
    state: link