---
- name: Deploy Serverside
  hosts: localhost
  become: yes
  vars_prompt:
    - name: "firstrun"
      prompt: "First run? (yes/no)"
      private: no

  pre_tasks:
    # Deploy swap file if necessary
    - name: Create swapfile
      command: fallocate -l 4G /swapfile
      when: firstrun == "yes"

    - name: Set permissions on swapfile
      file:
        path: /swapfile
        mode: '0600'
      when: firstrun == "yes"

    - name: Format swapfile
      command: mkswap /swapfile
      when: firstrun == "yes"

    - name: Enable swapfile
      command: swapon /swapfile
      when: firstrun == "yes"

  roles:
    - blocks-server