---
- name: Deploy Clientside
  hosts: all
  become: yes
  
  pre_tasks:
    - name: Install required system packages
      apt:
        name:
          - auditd
        state: present
        update_cache: yes
  
  roles:
    - ansible-wazuh-agent