---
- name: Deploy Clientside
  hosts: all
  become: yes
  
  pre_tasks:
    - name: Clone specific version of wazuh-ansible repo
      ansible.builtin.git:
        repo: https://github.com/wazuh/wazuh-ansible.git
        dest: "/home/ubuntu/blocks-lab/wazuh-ansible"
        version: "{{ wazuh_version }}"

    - name: Ensure symlink exists for wazuh role
      ansible.builtin.file:
        src: /home/ubuntu/blocks-lab/wazuh-ansible/roles/wazuh/ansible-wazuh-agent
        dest: /etc/ansible/roles/ansible-wazuh-agent
        state: link

    - name: Install required system packages
      apt:
        name:
          - auditd
        state: present
        update_cache: yes
  
  roles:
    - ansible-wazuh-agent