---
- name: Install Wazuh Agent
  hosts: all
  become: yes

  tasks:

  # Install Wazuh-ansible roles
  - name: Clone specific version of wazuh-ansible repo on controller
    ansible.builtin.git:
      repo: https://github.com/wazuh/wazuh-ansible.git
      dest: "/home/ubuntu/blocks-lab/wazuh-ansible"
    delegate_to: localhost
    run_once: true

  - name: Ensure symlink exists for wazuh role on controller
    ansible.builtin.file:
      src: /home/ubuntu/blocks-lab/wazuh-ansible/roles/wazuh-agent
      dest: /etc/ansible/roles/wazuh-agent
      state: link
    delegate_to: localhost
    run_once: true

  # Pre-requirements
  - name: Set hostname
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}"

  - name: Install required system packages
    apt:
      name:
        - auditd
      state: present
      update_cache: yes
    
  - name: Run Wazuh agent role
    ansible.builtin.include_role:
      name: wazuh-agent